common:
  ocr:
    baidu:
      appid: 11663730
      apikey: 8sqX8bWOAe0yPNLx4nqhySsy
      secret: 5qPW8QGbRG9luoRSYATmzszLqR6SU6cN
      language_type: CHN_ENG # 识别语言类型
      detect_direction: true # 是否检测图像朝向
      detect_language: true # 测试
      probability: true
    file:
      path: /tmp/orc/upload/
      keep: 1
spring:
  profiles:
    active: msg
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
logging:
  level:
    root: info
    com.baidu: info
  config: classpath:logback-spring.xml